server:
  port: 8002
spring:
  data:
    mongodb:
      URI: mongodb://localhost:27017/Person
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j.circuitbreaker:
    instances:
        operation:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 4
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10