server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/FranciscoCY/Entregable_uno
          search-path: config-data
  application:
    name: config-server